[theme]
base="light"
primaryColor="#e5007f"
backgroundColor="#f0f2f6"
secondaryBackgroundColor="#ffffff"
textColor="#2c3e50"
font="sans serif"

[client]
toolbarMode = "minimal"

[runner]
fastRerenderLimit = 0

[server]
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false

