# Supabase credentials
supabase_url = "https://evmidhomqllgvnudavgw.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2bWlkaG9tcWxsZ3ZudWRhdmd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA5ODcyODcsImV4cCI6MjA0NjU2MzI4N30.tScgF2uamrzkQtmaXiZ6ncBdfELGFA_3NFx1QCV-kv8"
# Add your service role key from Supabase dashboard
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2bWlkaG9tcWxsZ3ZudWRhdmd3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMDk4NzI4NywiZXhwIjoyMDQ2NTYzMjg3fQ.sZbk8PJ4kyFFiDtcrTAGuRPApv8_EnWENUQvKQonSSY"